export PATH=$PATH:/usr/local/bin
export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="agnoster"

plugins=(
  autojump
  git
  git-extras
  osx
  rbenv
  zsh-syntax-highlighting
  zsh-autosuggestions
)

# Local config
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

source $ZSH/oh-my-zsh.sh

source "$HOME/.oh-my-zsh/custom/themes/agnoster.zsh-theme"
